package:
  name: thread_tools
  version: 0.1

build:
  number: 0
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake
    - numpy
    - xtensor-python
    - cffi_practice

  run:
    - python
    - vs2015_runtime  # [win]
    - cffi_practice

test:
  imports:
    - thread_tools

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
