package:
  name: cffi_funs
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
  
source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake


about:
  summary: 'thread and clock utilities'
  description: 'functions to demonstrate cffi calling from python'

extra:
  recipe-maintainers:
    - phaustin

