package:
  name: cffi_funs
  version: 0.1
  
source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  summary: 'thread and clock utilities'
  description: 'functions to demonstrate cffi calling from python'

extra:
  recipe-maintainers:
    - phaustin

