package:
  name: thread_tools
  version: 0.1

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11 ==2.3
    - cmake
    - numpy    <1.12.2
    - xtensor-python ==0.13
    - cffi_practice

  run:
    - python
    - vs2015_runtime  # [win]
    - cffi_practice

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
